selected_type_value = "selected_type_value"
symbol_electric_heater_value = "symbol_electric_heater_value"
mass_value="mass_value"

electric_heater_plate_value = "entry_plate_electric_heater"
symbol_water_heater_value = "symbol_water_heater_value"
water_heater_plate_value = "water_heater_plate_value"
symbol_reverse_exchanger_value = "symbol_reverse_exchanger_value"
reverse_heater_plate_value = "reverse_heater_plate_value"
symbol_water_cooler_value = "symbol_water_cooler_value"
water_cooler_plate_value = "water_cooler_plate_value"
symbol_refrageration_cooler_value ="symbol_refrageration_cooler_value"
refrageration_cooler_plate_value = "refrageration_cooler_plate_value "
symbol_EC_supply_fan_value = "symbol_EC_supply_fan_value"
power_EC_supply_fan_value  = "power_EC_supply_fan_value "
voltage_EC_supply_fan_value = "voltage_EC_supply_fan_value,"
frequency_EC_supply_fan_value = "frequency_EC_supply_fan_value"
quantity_EC_supply_fan_value = "quantity_EC_supply_fan_value"
symbol_EC_exhaust_fan_value = "symbol_EC_exhaust_fan_value"
power_EC_exhaust_fan_value = "power_EC_exhaust_fan_value"
voltage_EC_exhaust_fan_value = "voltage_EC_exhaust_fan_value"
frequency_EC_exhaust_fan_value = "frequency_EC_exhaust_fan_value"
quantity_EC_exhaust_fan_value = "quantity_EC_exhaust_fan_value"
power_AC_supply_fan_value = "power_AC_supply_fan_value"
symbol_AC_supply_fan_value = "symbol_AC_supply_fan_value"
voltage_AC_supply_fan_value = "voltage_AC_supply_fan_value"
frequency_AC_supply_fan_value = "frequency_AC_supply_fan_value"
quantity_AC_supply_fan_value = "quantity_AC_supply_fan_value"
symbol_AC_exhaust_fan_value = "symbol_AC_exhaust_fan_value"
power_AC_exhaust_fan_value = "power_AC_exhaust_fan_value"
voltage_AC_exhaust_fan_value = "voltage_AC_exhaust_fan_value"
frequency_AC_exhaust_fan_value = "frequency_AC_exhaust_fan_value"
quantity_AC_exhaust_fan_value = "quantity_AC_exhaust_fan_value"
symbol_G4_supply_filter_value = "symbol_G4_supply_filter_value"
quantity_G4_supply_filter_value = "quantity_G4_supply_filter_value"
symbol_M5_supply_filter_value = "symbol_M5_supply_filter_value"
quantity_M5_supply_filter_value = "quantity_M5_supply_filter_value"
symbol_F7_supply_filter_value = "symbol_F7_supply_filter_value"
quantity_F7_supply_filter_value = "quantity_F7_supply_filter_value"
symbol_F9_supply_filter_value = "symbol_F9_supply_filter_value"
quantity_F9_supply_filter_value = "quantity_F9_supply_filter_value"




